### ISSUE TITLE
Sigma is not positive definite in mvnorm() call

### ISSUE THREAD

**Issue by acheng416** [JSB-UCLA/scDesign2#2]
Hi,

While running scDesign2 I received the following error:
![Screenshot_1](https://user-images.githubusercontent.com/47070554/124654800-00bb2b80-de6d-11eb-86fd-52b330cb0418.png)

The actual counts I used as input to scDesign2 were obtained from the Mouse Olfactory Bulb dataset from the following:
[https://www.spatialresearch.org/resources-published-datasets/doi-10-1126science-aaf2403/](url)

I was wondering if there is a way to resolve this issue?

**Comment by sunty17** [comment]
> Hi,
> 
> While running scDesign2 I received the following error:
> ![Screenshot_1](https://user-images.githubusercontent.com/47070554/124654800-00bb2b80-de6d-11eb-86fd-52b330cb0418.png)
> 
> The actual counts I used as input to scDesign2 were obtained from the Mouse Olfactory Bulb dataset from the following:
> [https://www.spatialresearch.org/resources-published-datasets/doi-10-1126science-aaf2403/](url)
> 
> I was wondering if there is a way to resolve this issue?

Hi Andrew,

Thank you for bringing this to our attention. Could you be a little bit more specific about how this issue came up? For example, I can see 12 replicate datasets plus 4 "layer" datasets in the link provided. Which count matrix did you use that gave rise to this issue? And did you filter for genes, perform any clustering or any value transformation? If you can provide the code that you used, It will be very helpful.

Best,
Tianyi

**Comment by acheng416** [comment]
Hi Tianyi,

Thank you for getting back to me. As of now, I need to isolate which replicate caused the issue. I will reply again once I can replicate the issue with more details.

Best,
Andrew

**Comment by sunty17** [comment]
> Hi Tianyi,
> 
> Thank you for getting back to me. As of now, I need to isolate which replicate caused the issue. I will reply again once I can replicate the issue with more details.
> 
> Best,
> Andrew

Sounds good!

**Comment by acheng416** [comment]
Hi Tianyi,

I tried again to replicate the error on Linux, but I was unable to. Thank you for your assistance.

Best,
Andrew
